# Generated by Django 5.1.2 on 2026-06-26 23:30

from django.db import migrations, models


def reasignar_funcionario_municipal(apps, schema_editor):
    """Convierte los usuarios con el rol eliminado 'funcionario_municipal'.

    El rol quedó sin funciones propias; su sucesor funcional es 'fiscalizador'
    (personal de gestión municipal).
    """

    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario.objects.filter(rol="funcionario_municipal").update(rol="fiscalizador")


def revertir_reasignacion(apps, schema_editor):
    """No-op: no es posible distinguir qué fiscalizadores provenían del rol anterior."""


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.RunPython(
            reasignar_funcionario_municipal,
            revertir_reasignacion,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('jefe_cuadrilla', 'Jefe de cuadrilla'), ('fiscalizador', 'Fiscalizador'), ('administrador', 'Administrador')], default='ciudadano', max_length=30),
        ),
    ]
