# Generated by Django 5.1.2 on 2025-11-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0011_denuncia_jefe_cuadrilla_historialestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='reporte_cuadrilla',
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='denuncia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_reporte_cuadrilla_rel', related_query_name='reporte_cuadrilla', to='denuncias.denuncia'),
        ),
    ]
